name: xml2json
version: 2.0.0
author: S. Hamblett <steve.hamblett@linux.com>
description: An XML to JSON conversion package.
homepage: https://github.com/shamblett/xml2json
documentation: http://oscf.org.uk/dart/api/xml2json/xml2json/Xml2Json.html
dependencies:
  browser: '>=0.9.0 <0.10.0'
  petitparser: '>=0.5.3 <0.5.4'
dev_dependencies:
  meta: any
  unittest: any
