name: xml2json
version: 1.1.0
author: S. Hamblett <steve.hamblett@linux.com>
description: An XML to JSON conversion package.
homepage: https://github.com/shamblett/xml2json
documentation: http://oscf.org.uk/dart/api/xml2json/xml2json/Xml2Json.html
dependencies:
  browser: '>=0.7.2+1 <0.7.3'
  petitparser: '>=0.5.3 <0.5.4'
dev_dependencies:
  json: any
  meta: any
  unittest: any
