name: xml2json
version: 4.1.0
author: S. Hamblett <steve.hamblett@linux.com>
description: An XML to JSON conversion package. Supports Badgerfish, GData and Parker conversions.
homepage: https://github.com/shamblett/xml2json

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  xml: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: '^1.3.0'
  coverage: '^0.12.3'
  dart_dev: '^2.0.1'
  dart_style: '^1.1.3'
  build_runner: '^1.3.1'
  build_test: '^0.10.6'
  build_web_compilers: '^1.2.0'