name: xml2json
version: 6.2.6
description: An XML to JSON conversion package. Supports Badgerfish, GData, OpenRally and Parker conversions.
repository: https://github.com/shamblett/xml2json
homepage: https://github.com/shamblett/xml2json

funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  xml: '^6.5.0'

dev_dependencies:
  test: '^1.25.14'
  lints: '^5.1.1'
  build_runner: '^2.4.14'
  build_test: '^2.2.3'
  build_web_compilers: '^4.1.0'
  dart_code_metrics_presets: '^2.21.0'

topics:
  - conversion
  - network
  - web
  - xml
  - json

screenshots:
  - description: 'Simple XML to JSON convertor'
    path: example/screenshots/xml2json.png