name: xml2json
version: 5.3.3
description: An XML to JSON conversion package. Supports Badgerfish, GData and Parker conversions.
homepage: https://github.com/shamblett/xml2json

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  xml: ^6.1.0

dev_dependencies:
  test: '^1.21.1'
  pedantic: '^1.10.0'
  lints: '^1.0.1'
  build_runner: '^2.1.11'
  build_test: '^2.1.5'
  build_web_compilers: '^3.2.3'
