name: xml2json
version: 5.3.3
description: An XML to JSON conversion package. Supports Badgerfish, GData and Parker conversions.
homepage: https://github.com/shamblett/xml2json

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  xml: ^6.1.0

dev_dependencies:
  test: '^1.16.2'
  pedantic: '^1.10.0'
  pana: '^0.15.3'
  build_runner: '^1.11.1'
  build_test: '^1.3.6'
  build_web_compilers: '^2.11.0'
