name: xml2json
version: 5.3.6
description: An XML to JSON conversion package. Supports Badgerfish, GData and Parker conversions.
repository: https://github.com/shamblett/xml2json
homepage: https://github.com/shamblett/xml2json

funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  xml: ^6.1.0

dev_dependencies:
  test: '^1.21.1'
  pedantic: '^1.10.0'
  lints: '^2.0.0'
  build_runner: '^2.1.11'
  build_test: '^2.1.5'
  build_web_compilers: '^3.2.3'
